name: Deploy to Pypi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.7"

      - name: Install Poetry & Tox
        run: pip install poetry tox

      - name: Install Dependencies
        run: poetry install

      - name: Run Tox
        run: tox -e py37

      - name: Poetry Publish
        run: |
          poetry build -f sdist
          poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
